package modelsEx;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import modelsEx.FoodieMember;
import modelsEx.FoodieMemberExample;



//DAO 역할
public interface FoodieMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOT.FOODIE_MEMBER
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    long countByExample(FoodieMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOT.FOODIE_MEMBER
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    int deleteByExample(FoodieMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOT.FOODIE_MEMBER
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    int deleteByPrimaryKey(String nickname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOT.FOODIE_MEMBER
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    int insert(FoodieMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOT.FOODIE_MEMBER
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    int insertSelective(FoodieMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOT.FOODIE_MEMBER
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    List<FoodieMember> selectByExample(FoodieMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOT.FOODIE_MEMBER
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    FoodieMember selectByPrimaryKey(String nickname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOT.FOODIE_MEMBER
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    int updateByExampleSelective(@Param("record") FoodieMember record, @Param("example") FoodieMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOT.FOODIE_MEMBER
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    int updateByExample(@Param("record") FoodieMember record, @Param("example") FoodieMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOT.FOODIE_MEMBER
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    int updateByPrimaryKeySelective(FoodieMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROOT.FOODIE_MEMBER
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    int updateByPrimaryKey(FoodieMember record);
}