package modelsEx;

//데이터를 전송해주는 DTO 역할

public class FoodieMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOT.FOODIE_MEMBER.NICKNAME
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOT.FOODIE_MEMBER.PWD
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROOT.FOODIE_MEMBER.EMAIL
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOT.FOODIE_MEMBER.NICKNAME
     *
     * @return the value of ROOT.FOODIE_MEMBER.NICKNAME
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOT.FOODIE_MEMBER.NICKNAME
     *
     * @param nickname the value for ROOT.FOODIE_MEMBER.NICKNAME
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOT.FOODIE_MEMBER.PWD
     *
     * @return the value of ROOT.FOODIE_MEMBER.PWD
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOT.FOODIE_MEMBER.PWD
     *
     * @param pwd the value for ROOT.FOODIE_MEMBER.PWD
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROOT.FOODIE_MEMBER.EMAIL
     *
     * @return the value of ROOT.FOODIE_MEMBER.EMAIL
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROOT.FOODIE_MEMBER.EMAIL
     *
     * @param email the value for ROOT.FOODIE_MEMBER.EMAIL
     *
     * @mbg.generated Thu Mar 15 13:25:02 KST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }
}